# Generated by Django 4.1.3 on 2022-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LeadGenerationAPP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photograph",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
