# Generated by Django 4.1.3 on 2022-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LeadGenerationAPP", "0005_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="", max_length=45)),
                ("lastname", models.CharField(default="", max_length=45)),
                ("dob", models.DateField()),
                ("gender", models.CharField(default="", max_length=6)),
                ("emailid", models.CharField(default="", max_length=45)),
                ("mobileno", models.CharField(default="", max_length=12)),
                ("alternateno", models.CharField(default="", max_length=12)),
                ("address", models.CharField(default="", max_length=200)),
                ("state", models.CharField(default="", max_length=45)),
                ("city", models.CharField(default="", max_length=45)),
                ("photograph", models.ImageField(upload_to="static/")),
            ],
        ),
    ]
