# Generated by Django 4.1.3 on 2022-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LeadGenerationAPP", "0006_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="organizationname",
            field=models.CharField(default="", max_length=45),
        ),
    ]
