# Generated by Django 4.1.3 on 2022-12-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LeadGenerationAPP", "0007_customer_organizationname"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(default="", max_length=45),
        ),
        migrations.AddField(
            model_name="manager",
            name="password",
            field=models.CharField(default="", max_length=45),
        ),
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.DateField(default=""),
        ),
    ]
