# Generated by Django 4.1.3 on 2022-12-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LeadGenerationAPP", "0008_employee_password_manager_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="gender",
        ),
    ]
