# Generated by Django 4.1.3 on 2023-01-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LeadGenerationAPP", "0011_calldetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calldetail",
            name="transactionid",
        ),
    ]
